# Generated by Django 3.0.2 on 2020-01-07 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_auto_20200107_1457'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examplebucketlist',
            options={},
        ),
    ]
